

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Roman-Svyshch/eazyBank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true


#        native:
##          search-locations: "classpath:/config"
#          search-locations: "file:///C://Users//I//Documents//config"


management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "19EEB9391B777FE33A8AF5D18C7AA"
server:
  port: 8071